import type { Metadata } from "next";
import "./globals.css";
import BodyLines from "@/components/shared/BodyLines";
import localFont from "next/font/local";
import { Inter } from "next/font/google";

const clashDisplay = localFont({
  src: [
    {
      path: "../public/fonts/clash-display/ClashDisplay-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../public/fonts/clash-display/ClashDisplay-Variable.woff",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../public/fonts/clash-display/ClashDisplay-Variable.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-clash-display",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-inter",
});

console.log(inter.variable);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplay.variable} ${inter.variable} antialiased relative overflow-x-hidden dark`}
      >
        <BodyLines cols={4} />
        <main className="relative">{children}</main>
      </body>
    </html>
  );
}
